sylius_grid:
    templates:
        filter:
            facets_filters: "@AsdoriaSyliusFacetFilterPlugin/Grid/Filter/facetsFilters.html.twig"
    grids:
        sylius_shop_product:
            filters:
                facets_filters:
                    type: facets_filters
                    label: false
                    options: 
                        owner: taxon
                        filterBy: owner
