asdoria_admin_facet_filter:
  resource: |
    alias: asdoria.facet_filter
    section: admin
    templates: '@SyliusAdmin\\shared\\crud'
    except: ['show']
    redirect: update
    grid: asdoria_admin_facet_filter
    permission: true
    vars:
       update:
         templates:
            toolbar: "@AsdoriaSyliusFacetFilterPlugin/FacetFilter/Update/_toolbar.html.twig"
  type: sylius.resource


asdoria_admin_facet_filter_facet:
    resource: facet.yaml
    prefix: /facet-filter/{facetFilterId}
